site_name: Portfólio 5 de Inteligência Artificial

markdown_extensions:
  - pymdownx.arithmatex
  - admonition
  - toc:
      permalink: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/MathJax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

theme:
   name: material 
   palette:
    - scheme: default
      toggle: 
         icon: material/toggle-switch-off-outline
         name: Dark mode
      primary: blue
    - scheme: slate
      toggle:
         icon: material/toggle-switch
         name: Light mode

nav:
  - Impressões gerais: index.md
  - Referencias: references.md