site_name: Portfólio 5 de Inteligência Artificial

theme:
   name: material 
   palette:
    - scheme: default
      toggle: 
         icon: material/toggle-switch-off-outline
         name: Dark mode
      primary: blue
    - scheme: slate
      toggle:
         icon: material/toggle-switch
         name: Light mode

nav:
  - Impressões gerais: index.md
  - Referencias: references.md