site_name: Portfólio 5 de Inteligência Artificial

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

theme:
   name: material 
   palette:
    - scheme: default
      toggle: 
         icon: material/toggle-switch-off-outline
         name: Dark mode
      primary: blue
    - scheme: slate
      toggle:
         icon: material/toggle-switch
         name: Light mode

nav:
  - Impressões gerais: index.md
  - incerteza: uncertainty.md
  - Utilidade: utility.md
  - Teoria de Decisão: decision.md
  - Notação básica de probabilidade: basic_notation.md
  - Independência e independência condicional: independence.md
  - Regra de Bayes, aplicações e modelo ingênuo: bayes_rule.md
  - Redes Bayesianas: bayesian_network.md
  - Inferência: inference.md
  - Tempo e incerteza: time_uncertainty.md
  - Estados e observações: states_observations.md
  - Modelo de transição e modelos de sensores: transition_sensors.md
  - Inferência em modelos temporais: temporal_inference.md
  - Modelo Oculto de Markov: hidden_markov.md
  - Filtros de Kalman: kalman_filter.md
  - Conclusões: conclusions.md
  - Referencias: references.md